before_script:
  - apt-get update
  - apt-get install -y software-properties-common   # Provides add-apt-repository
  - add-apt-repository ppa:deadsnakes/ppa           # Provides python3.6
  - apt-get update

  - apt-get install -y texlive-full
  - apt-get install -y python-pygments
  - apt-get install -y git
  - apt-get install -y ghostscript

  - apt-get install -y python3.6 python3-pip
  - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 10
  - python3.6 -m pip install -r requirements.txt

job:
  image: ubuntu:16.04
  script:
    - git submodule update --init --recursive
    - ./compile.sh
  artifacts:
    paths:
      - specification/out/UAVCAN_Specification.pdf
